### ISSUE TITLE
How to install the packages in mexfiles?

### ISSUE THREAD

**Issue by Ian-Liao** [EvZissel/LoBCoD#1]
Hi Ev Zisselman,

I tried to run the Demo.m but I got this error:
`Attempt to execute SCRIPT im2colstep as a function:
/Users/ian/opensource/LoBCoD/mexfiles/im2colstep.m

Error in myim2col_set_nonoverlap (line 10)
        patches{cnt} = im2colstep(tmp, [n,n], [n,n]);

Error in LoBCoD (line 122)
    resI_patches{i} = myim2col_set_nonoverlap(noisyI{i}, n);

Error in Demo (line 36)
[cleanI,objective_LoBCoD,avgpsnr_LoBCoD,sparsity_LoBCoD,totTime_LoBCoD,alpha,D_LoBCoD] =
LoBCoD(params);`

I ran this project on MacOS. Could you tell me how to fix this?

Thank you,
Ian

**Comment by EvZissel** [comment]
Hi Ian,

The function `im2colstep(A,[N1 N2])` is a faster implementation of Matlab's built in function `im2col(A,[N1 N2],'sliding')` documented [here](https://www.mathworks.com/help/images/ref/im2col.html). 
You can replace `im2colstep` with Matlab's `im2col` to produce the same output.

Alternatively, you can compile the mex files by following the instructions [here](http://www.cs.technion.ac.il/~ronrubin/software.html) :

- Note: You may need to install both OMP-Box v10 (necessary for KSVD-Box) and KSVD-Box v13 (which contains `im2colstep`)

Please let me know if I can help any further, 
Ev

**Comment by Ian-Liao** [comment]
Hi Ev,

I've fixed this problem. It turns out that I have to download the col2imstep.mexmaci64 and im2colstep.mexmaci64 files and put them into the mexfiles path for the MacOS environment.

Thank you anyway,
Ian
